version: "3.8"
name: monitor
services:
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.26.0
    env_file: .env
    restart: always
    ports:
      - ${ALERTMANAGER_PORT}:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.48.0
    user: root
    env_file: .env
    restart: always
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.0.10
    user: root
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
