name: monitor
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.48.0
    user: root
    env_file: .env
    restart: always
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:v0.25.0
    user: root
    env_file: .env
    restart: always
    ports:
      - ${BLACKBOX_PORT}:9115
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.0.10
    user: root
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    extra_hosts:
      - host.docker.internal:host-gateway
